# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 10 Apr 2015 19:06:49 +0000
*               @ALL          1
*               @user         8
